### ISSUE TITLE
Cached follower usernames aren't ever updated

### ISSUE THREAD

**Issue by keysmashes** [rswestmoreland/unfollowbugbot#2]
Twitter usernames can change! Unfortunately unfollowbugbot doesn't seem to notice when that happens, and keeps messaging people with their old username :(

I guess unfollowing and following would fix this? But I don't know how often the bot checks who's following it.

**Comment by keysmashes** [comment]
Unfollowing and refollowing apparently does not fix this, unfortunately.

**Comment by rswestmoreland** [comment]
This was fixed on 2020-09-02.
